### ISSUE TITLE
Easily re-run lint-suite directory while watching

### ISSUE THREAD

**Issue by arronmabrey** [rizowski/eslint-watch#11]
Maybe this already exists and I didn't see it, but would it be possible to easily re-run the full lint-suite while you are already watching. Perhaps hitting the enter key could trigger a full suite re-run.

**Comment by rizowski** [comment]
Thanks for suggesting this. Its not currently a feature. I have had the same thought when trying to fix a bunch of errors in various files.

**Comment by arronmabrey** [comment]
Yup, that is exactly my use case. :-)

In the ruby world there is a project called guard, it's a general file
watcher library, it allowed you to hit the "enter" key and it would re run
everything for you. It was very handy.

**Comment by rizowski** [comment]
I'll take a look at it. I can't guarantee that I will get to it soon, but it has been on my mind. If you want to you can submit a pull request if I am taking too long to get it in. :smile:

**Comment by rizowski** [comment]
@arronmabrey This has been added to PR #25 I will review it tomorrow morning and see if it is still working. If everything checks out, it will be released with 2.0.0.

**Comment by arronmabrey** [comment]
Awesome work! Thanks!

**Comment by rizowski** [comment]
This is now been released with 2.0.0
