### ISSUE TITLE
Clear terminal on each eslint run?

### ISSUE THREAD

**Issue by svicalifornia** [rizowski/eslint-watch#110]
Is there an option to clear the Terminal each time eslint is run, to show only the results of the last run?

**Comment by rizowski** [comment]
@svicalifornia Thanks for the PR and this request. I'll get to it ASAP

**Comment by rizowski** [comment]
This has been released with[ V3.1.0](https://github.com/rizowski/eslint-watch/releases/tag/v3.1.0)
