### ISSUE TITLE
Is it possible to trigger something on error?

### ISSUE THREAD

**Issue by lucastobrazil** [rizowski/eslint-watch#129]
Hey there,
Love this project! the setup was smooth and easy :)

This is more of a question rather than an issue... I'd like to have the ability to make my terminal 'beep' if there is an error while watching. Is it possible to hook into ESW to trigger `beep()` for instance (from this project: https://github.com/feross/beepbeep)?

Cheers,
Lucas

**Comment by rizowski** [comment]
As is, there isn't a way to currently do this.  Do you have any ideas on how this could be accomplished?

**Comment by lucastobrazil** [comment]
@rizowski I know for running eslint in a gulp task you can usually pipe in other functions (or use gulp-notify https://github.com/mikaelbr/gulp-notify) - is there any kind of callbacks that could be hooked into with eslint-watch?

**Comment by rizowski** [comment]
Whoops sorry for such a late response. No there isn't a way. This project was meant to just provide a way to have a file watch for eslint. It doesn't provide much more than what the CLI can offer.
