### ISSUE TITLE
Option to not print "clean" message; only errors

### ISSUE THREAD

**Issue by simison** [rizowski/eslint-watch#147]
When running the linter, would be wonderful to hide "clean" messages and leave only error messages:

<img src="https://user-images.githubusercontent.com/87168/50387380-06afed80-0703-11e9-8760-42967bbca9b6.png" alt="" width="350"/>

I'm running:
```bash
esw --watch --quiet --cache .
```

I actually expected `--quiet` not to print the success message. :-)

But it obviously is meant to output it:
https://github.com/rizowski/eslint-watch/blob/87396b7e4c00aab6685c4237645d44153555c2fd/tests/integration/integration-spec.js#L199-L204

**Comment by rizowski** [comment]
Could I interest you in `--clear`? While it won't stop showing the clean message, it will clear your terminal for every run. I think this is a valid issue, I'll be sure to include it in the next release.

**Comment by luanlucho** [comment]
Hi,

I will be great if you could provide a flag to silence the success messages.

Hope you can add this feature soon.

**Comment by rizowski** [comment]
@luanlucho I did make it respect the `--quiet` flag. Does that not suffice?

**Comment by luanlucho** [comment]
I don’t think it is.

It will be nice to have flag that will just silence the success messages, but keeps the warnings and errors intact.

Hope that sounds like a good idea to you.
