### ISSUE TITLE
Returns different result from eslint

### ISSUE THREAD

**Issue by strowk** [rizowski/eslint-watch#169]
### Environment

  - Node Version: v12.19.0
  - Eslint-Watch Version: Eslint-Watch: v7.0.0
  - Eslint Version: v7.15.0

### Basic Description of the problem

If I run `eslint  ./src --ext .js --ext .ts --ext .tsx`, it gives output 
```
✖ 1 problem (0 errors, 1 warning)
```

but esw says "Clean"
```
 esw -w  ./src --ext .js --ext .ts --ext .tsx 
✓ Clean (5:36:27 PM)
```

### How to reproduce it

  1. Command: `esw -w  ./src --ext .js --ext .ts --ext .tsx`
  2. should give same output as `eslint  ./src --ext .js --ext .ts --ext .tsx`

### Debug output:

```
  esw:eslint Executing [ '--ext', [ '.js', '.ts', '.tsx' ], './src' ] +0ms
  esw:eslint {
  esw:eslint   command: 'eslint --ext .js,.ts,.tsx ./src',
  esw:eslint   exitCode: 0,
  esw:eslint   stdout: '',
  esw:eslint   stderr: '',
  esw:eslint   all: undefined,
  esw:eslint   failed: false,
  esw:eslint   timedOut: false,
  esw:eslint   isCanceled: false,
  esw:eslint   killed: false
  esw:eslint } +1s
✓ Clean (5:41:46 PM)
```

**Comment by rizowski** [comment]
This is by design. There have been suggestions for turning it off. What is your use case?
