### ISSUE TITLE
ESLint 8 support

### ISSUE THREAD

**Issue by gabor-at-reed** [rizowski/eslint-watch#177]
### Environment

  - Node Version: 16.x LTS
  - Eslint-Watch Version: 7.0
  - Eslint Version: 8.1

### Basic Description of the problem

Any plans to add support to ESLint 8.x? Currently, it doesn't work with any newer versions of ESLint. 8.1 is the stable version now and 7 is deprecated.

Cheers!

**Comment by rizowski** [comment]
Hey thanks for posting. Yeah I'll see if I can get a new version out today, if not this weekend.

**Comment by rizowski** [comment]
This has been resolved in the latest 8.0.0 version
