### ISSUE TITLE
Add a flag to turn on full directory lint on every file save

### ISSUE THREAD

**Issue by rizowski** [rizowski/eslint-watch#29]
Idea first presented by: @zack37

While there is a way to trigger a full directory lint while watching ( #11 ); it would be nice to be able to set a flag that overrides the single file lint functionality so you don't have to hit `enter` if you don't want to. ~~This feature may not be a desired thing for older projects that are trying to get into the practice of linting. So this feature should be an opt-in flag.~~ It probably doesn't matter if it is an opt-in feature anymore with this going to a 3.0.0 release. By default the `--changed` will enable single file linting on `--watch`

The expected flag could be something along the lines of `esw -w --changed`. This flag might need to be a conditional flag, where it can only be used if the `watch` flag is enabled.

**Comment by isTravis** [comment]
:+1: to this enhancement.

**Comment by jeron-diovis** [comment]
+1, waiting for this very much

**Comment by rizowski** [comment]
Alright, I will begin working on this feature. I cannot guarantee that it will be finished quickly but I will try my best. Thanks @jeron-diovis  and @isTravis for bumping this enhancement.

**Comment by ejfrancis** [comment]
:+1: this would be great

**Comment by s9tpepper** [comment]
its the first thing that I was looking for after using it for the first time. 👍

**Comment by rizowski** [comment]
I am going to be gone for a couple of weeks but when I get back I will implement this enhancement. Thanks guys for the 👍

**Comment by kellyrmilligan** [comment]
maybe i'm missing something here. a while back I used this and it was great. i'm setting it up again for a new project, and now when I change a file, it is not re-running. is the default behaviour different now?  on every file change, I want to lint the changed file. is this off by default?

**Comment by kellyrmilligan** [comment]
My bad sorry I forgot the . For the extension. I think -- debug is broken btw.

**Comment by rizowski** [comment]
@kellyrmilligan Can you explain a little more. It sounds like there might be a bug with default directory linting. Eslint-watch should default to ./ if you don't provide a directory. But also to the full directory lint a really really young version of Eslint-Watch I believe had this feature. It was later changed to do a single file since at the time I was working on a large project with over 20,000 lint errors and it was impossible to find the file I was working on.  But I don't think it has been a feature since pre 1.0.0

**Comment by kellyrmilligan** [comment]
Yes sorry, it was all my bad. I had --ext es6 and not .es6, so the full lint worked initially, then. It big afterwords. I tried enabling -- debug but just eventually did DEBUG=* before exciting the command to figure it out and also logging more in the code.

**Comment by cbacon91** [comment]
This is a very required feature and would please me greatly 👍

**Comment by rizowski** [comment]
This issue is now in master awaiting a release
