### ISSUE TITLE
Improving quiet flag

### ISSUE THREAD

**Issue by Cordazar** [rizowski/eslint-watch#46]
Either the --quiet flag should also mute the esw "Linting:" output or there should be another flag for that purpose. 
As it stands now if you have many separate files to lint you fill up the terminal with a long unreadable block of files.

**Comment by rizowski** [comment]
@Cordazar Thanks for posting this. I wasn't sure it was really helpful or not and have been juggling the idea of throwing it out entirely. I am thinking about pulling the linting message into debug logging.

**Comment by Cordazar** [comment]
@rizowski That sounds like a good idea, in debug logging you can choose to view it if and when you need it.

**Comment by rizowski** [comment]
I took out the Linting ... and Watching ... messages since they really are for debugging purposes. This should be in the branch `watch-fix` As soon as #47 is verified as being fixed, this will go out with those changes on version 2.1.3.

**Comment by rizowski** [comment]
This has been release with v2.1.3
