### ISSUE TITLE
Please support eslint 1.1.0

### ISSUE THREAD

**Issue by mastertinner** [rizowski/eslint-watch#8]

**Comment by rizowski** [comment]
This will be in the 2.0.0 release.

**Comment by rizowski** [comment]
I actually haven't ran into any problems with using ESLint 1.1.0 so I am going to make a patch and publish just that change. That way people can still use ESW and have the latest changes with ESLint up to 2.0.0

**Comment by rizowski** [comment]
This was released with [v1.2.5](https://github.com/rizowski/eslint-watch/releases/tag/v1.2.5)

**Comment by mastertinner** [comment]
Great stuff. Thanks @rizowski !
