### ISSUE TITLE
Error parsing type '--no-color'

### ISSUE THREAD

**Issue by rivertam** [rizowski/eslint-watch#81]
I'm not specifying any options, but I'm getting this error on `esw`

Node version: v5.10.1
eslint version: v2.9.0

Logs: (ran `DEBUG=* esw`)
```
  esw:eslint-cli Loaded +0ms
  esw:eslint-cli EsLint path: /Users/ben/frontend/node_modules/.bin/eslint +3ms
  esw:eslint-help Loaded +33ms
  esw:options Loaded +18ms
  esw:success-formatter loaded +226ms
  esw:simple-detail loaded +2ms
  esw:watcher Loaded +0ms
  esw:arg-parser Loaded +0ms
  esw:esw-cli Loaded +1ms
  esw:esw-cli Eslint-Watch: 2.1.10 +0ms
  esw:eslint-help Executing help +0ms
  esw:eslint-cli eslint: [ '--help' ] +0ms
  esw:eslint-help Help text received +254ms
  esw:eslint-help noAlias +1ms false
  esw:eslint-help Alias found: -c +0ms
  esw:eslint-help Parsing --config +0ms
  esw:eslint-help noAlias +1ms true
  esw:eslint-help Parsing --no-eslintrc +0ms
  esw:eslint-help Parsing no option +0ms --no-eslintrc
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --env +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --ext +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --global +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --parser +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --parser-options +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --cache +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --cache-file +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --cache-location +1ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --rulesdir +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --plugin +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --rule +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --ignore-path +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --no-ignore +0ms
  esw:eslint-help Parsing no option +0ms --no-ignore
  esw:eslint-help noAlias +1ms true
  esw:eslint-help Parsing --ignore-pattern +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --stdin +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --stdin-filename +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --quiet +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --max-warnings +0ms
  esw:eslint-help noAlias +0ms false
  esw:eslint-help Alias found: -o +0ms
  esw:eslint-help Parsing --output-file +0ms
  esw:eslint-help noAlias +1ms false
  esw:eslint-help Alias found: -f +0ms
  esw:eslint-help Parsing --format +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --color +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --init +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --fix +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --debug +0ms
  esw:eslint-help noAlias +0ms false
  esw:eslint-help Alias found: -h +0ms
  esw:eslint-help Parsing --help +0ms
  esw:eslint-help noAlias +0ms false
  esw:eslint-help Alias found: -v +0ms
  esw:eslint-help Parsing --version +0ms
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --no-inline-config +0ms
  esw:eslint-help Parsing no option +0ms --no-inline-config
  esw:eslint-help noAlias +0ms true
  esw:eslint-help Parsing --print-config +0ms
[Error: Option 'color': Error parsing type '--no-color': Unexpected character: - - Remaining tokens: ["-","-","no","-","color"] - Initial input: '--no-color']
```

**Comment by rizowski** [comment]
@rivertam I noticed this today as well. Thanks for posting.

**Comment by rizowski** [comment]
This issue most likely resides in the help parser. Formatting or spaces might have changed. It will be the first thing to break since it needs to run before anything else can occur.

**Comment by rivertam** [comment]
Of course. Thanks for the quick response.

**Comment by rizowski** [comment]
@rivertam This should be fixed on OSX and Linux. I am currently verifying it is fixed on Windows.
https://github.com/rizowski/eslint-watch/pull/83
Could you please use the ew-81 branch and verify it is also fixed for you?

**Comment by rivertam** [comment]
Well, I don't really know how to do that, but I did the following:

1. Clone the repo
2. Check out the ew-81 branch
3. Run `npm i -g .` inside the folder
4. Try `esw` in my own repository

and I get 
![screen shot 2016-05-03 at 1 21 37 pm](https://cloud.githubusercontent.com/assets/4165105/14991979/fdd795f6-1131-11e6-8789-434d331a2203.png)

**Comment by rivertam** [comment]
My package.json is specified in /Users/ben/frontend, not /Users/frontend/build/

**Comment by rizowski** [comment]
Try this

  1. `git clone https://github.com/rizowski/eslint-watch.git -b ew-81`
  2. `npm i && npm link`
  3. CD into the project you saw the error
  4. `esw`

Another way of doing it is specifying it in your `package.json`

```json
...
"scripts": {
  "lint": "esw --quiet"
},
...
"devDependencies": {
  "eslint-watch": "rizowski/eslint-watch#ew-81"
}
```
`npm run lint`

**Comment by rizowski** [comment]
Can you run it with `DEBUG=* esw` so I can see what it is doing?

**Comment by rivertam** [comment]
![screen shot 2016-05-03 at 2 02 17 pm](https://cloud.githubusercontent.com/assets/4165105/14993199/af6e15a6-1137-11e6-9d2d-261ad71c272a.png)

**Comment by rizowski** [comment]
@rivertam Do you have any other projects you can test this on?

**Comment by rivertam** [comment]
@rizowski Hmm, yeah it seems to be working on another repo, but it's not actually watching. Just says "clean" and then exits (not sure if this is normal behavior). I am trying to use this within `frontend` though.

I'd include the debug logs for the "working" repo, but they're insanely long (over 1000 lines long; not sure how much)

**Comment by rizowski** [comment]
I think for the first project you just need to add an ignore rule for your build folder. It looks like it is trying to lint your build folder, which in my experience I haven't wanted to do since I am either building my assets, minifying code, etc etc.. Is that the case here?

**Comment by rivertam** [comment]
Ah, yeah, that seems to be the problem. It's still exiting immediately, but that's a PEBKAC error; just forgot to specify `-w` flag haha.

**Comment by rivertam** [comment]
Thank you!

**Comment by rizowski** [comment]
Cool, I am going to pull this in and publish 2.1.11

**Comment by rizowski** [comment]
2.1.11 has been released: 
https://github.com/rizowski/eslint-watch/releases/tag/v2.1.11
https://www.npmjs.com/package/eslint-watch
