### ISSUE TITLE
watch exits after file change

### ISSUE THREAD

**Issue by reharik** [rizowski/eslint-watch#85]
Hi I am running the command 
esw . -w 
from the root of the project. it runs the lint but when I make a change in a file and go back to console it exits.  
Am I doing something wrong?
R

**Comment by rizowski** [comment]
Thanks for posting an issue @reharik .

Can you run the command with the debug environment variable set. (`DEBUG=* esw -w`) Also I need to know the versions of `eslint`, `eslint-watch`, `npm` and `node` you are using as well as what `OS` you are running it with.

**Comment by reharik** [comment]
Hey, 
So I gto eslint to pass and now it doesn't seem to be exiting, however, I'm going to merge this "eslint branch" into master pretty soon, at which point there will be a ton of errors and I'll probably experience the problem again.  At that point I will inspect the debug out put.
for now I'm using 
"eslint": "^2.11.1",
eslint-watch 2.1.11
node 4.4.5
npm 2.15.5
which is strange, not sure why I'm on npm 2.15 but I'll wait to update till we resolve this so I don't skew the data.
r

**Comment by reharik** [comment]
Hi, 
So upon my merge I did have a bunch of errors, but the watch started working.  I did add airbnb and some customization to my eslintrc but I"m not sure what made the watch work again.  
I suspect that is unsatisfying from a discovery perspective.  Sorry.
while I got you is there a way to make it reload on focus ( of console ) rather than having to hit return?
Thanks,
Raif

**Comment by rizowski** [comment]
@reharik Glad to see you were able to get it working. As of right now there isn't a way to get it to relint on console focus. I am not sure if that is even possible. 

If you have any other problems, please don't hesitate to open another issue.
