### ISSUE TITLE
command line is do twice?

### ISSUE THREAD

**Issue by wklc2014** [rizowski/eslint-watch#95]
![image](https://cloud.githubusercontent.com/assets/7589922/21519718/5adc726c-cd2a-11e6-816f-90d4f9edbe4d.png)

`esw -w`
It check twice?

**Comment by rizowski** [comment]
@wklc2014 Do you have anything else running? (ex. Webpack)

**Comment by rizowski** [comment]
With no additional information I am closing this issue.

**Comment by jeremejevs** [comment]
@rizowski I'm observing this too:

```
C:\src\index.js (1/0)
  ✖  14:7  'x' is assigned a value but never used  no-unused-vars

✖ 1 error (12:59:38)

C:\src\index.js (1/0)
  ✖  14:7  'x' is assigned a value but never used  no-unused-vars

✖ 1 error (12:59:38)
```

Sometimes it triggers twice, sometimes once, no way to predict. This happens if I `esw --watch src`. If I do `esw --watch src/index.js` instead, then the problem goes away. There are no other files in `src`. This is on Windows, latest everything.
